[package]
name = "diary"
version = "0.1.0"
authors = ["masuke5 <s.zerogoichi@gmail.com>"]

[dependencies]
clap = "2.32.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
failure = "0.1.2"
ansi_term = "0.11"
regex = "1"

[dependencies.chrono]
version = "0.4"
features = ["serde"]
